name: audio_recorder_example
description: Demonstrates how to use the audio_recorder plugin.

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.1.0
  file: ^6.1.2

environment:
  sdk: ">=2.0.0-dev.40.0.flutter-f981f09760 <3.0.0"

dev_dependencies:
  audio_recorder:
    path: ../
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
